language: node_js
sudo: false
node_js:
  - "9.2"
addons:
  postgresql: "9.6"
install:
  - npm install
test:
  - npm test
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  slack:
    secure: H4SdqAPX95FWZkz44rICFn0xjaQWfYS5SRNLv5iFAA4ARZFillcIsWZiH+7ZE577eXmk57fr61XuJkRj8IJPn9A/TnTwF+LOPVARCEIZsEMUU4N9bAQs+ssECKBXvutDomjw6VKYGZRfaG5OEOvhCquynnITXyONgHMz9SadJdv2EgeSrb8gepKRdggQC7+TJkf1fMTTewAfJVZeuM/TSeeez7DsOPcGPoYwhOlyXzx94CP5ryrOtsCmNKk+01w+CjL6mHLotftSGjkoAYh1wKrWOHwUgLJR+YYPv16AlT8RyBcfp8+ZN6EqENnFXuXeUUnMSlNIXcroCebSF8DKVPM44bF0GO/pUhTfiE8Iz0iqfDplVPhSJN0Tr9R0RhoETb4WSKtM2VgiFu0xGDgfM9N6fdU2XP6fzhFVcUmR5s2vpthRzS+M7L8ju0DyasFV3xzC62JSHDVy+NyNQlRRQ2fNR9JJ9EFccUGY5v04GNUMXshzmCZnVX3QSBSBqC2rxgFXDEI31PGtvGAe7S4UE31vyP1TyMB7ShNP53eFeY4HPQKl7s60cwlPZ4ocTnNKgS9FCjdRO9KqBDo6WS2Kl7JyukIs3ArkkZantenj4xBsvgxDdfoQM5vEzfwv2Ku91Bes/MUoEdEdLu2qH2LeWILTdpQEWlq0aUM614UcFpo=
    on_success: always
    on_failure: always
  email:
    on_success: never # default: change
    on_failure: change # default: always